(print (list 'Fred 'and 'Wilma))
(print (list 'Fred '(and Wilma)))
(print (cons Nil Nil))
(print (cons T Nil))
(print (cons Nil T))
(print (list Nil))
(print (cons '(T) Nil))
(print (list '(one two) '(free temp)))
(print (cons 'Fred '(and Wilma)))
(print (cons 'Fred '(Wilma)))
(print (list Nil Nil))
(print (list T Nil))
(print (list Nil T))
(print (cons T (list Nil)))
(print (list '(T) Nil))
(print (cons '(one two) '(free temp)))
