(defun fst_is_med (num1 num2 num3)
    (if (> num1 num2)
        (< num1 num3)
        (if (> num1 num3)
            (< num1 num2))))

(defun fst_is_med (num1 num2 num3)
    (cond   (   (> num1 num2)
                (cond ((< num1 num3))))
            (   (> num1 num3)
                (cond ((< num1 num2))))))

(defun fst_is_med (num1 num2 num3)
    (or (and    (> num1 num2)
                (< num1 num3))
        (and    (> num1 num3)
                (< num1 num2))))
